version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB : myproject_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:5.0
    command: redis-server
    ports:
      - '6379:6379'

  web:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - REDIS_URL=redis://redis:6379/1

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - '.:/app'
    ports:
      - "5050:80"
    restart: always
  
  worker:
    depends_on:
      - db
      - redis
    build: .
    command: bundle exec sidekiq -q default -q mailers
    volumes:
      - '.:/myapp'
    environment:
    - REDIS_WORKER_URL=redis://redis:6379/0
